Add lua-resty-jwt to nginx image
verrazzano/ingress-nginx pull request #13
Opened 2021-01-18 11:56 UTC by lake-of-dreams

## What this PR does / why we need it:
The nginx image built using this repository is going to be used for the api server for verrazzano which will perform JWT validation from the console UI. This requires the `lua-resty-jwt` lua module to be installed. Also few libraries are updated to mitigate reported security vulnerabilities.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Which issue/s this PR fixes

## How Has This Been Tested?
Manually tested by using the image as api server

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/kubernetes/ingress-nginx/blob/master/CONTRIBUTING.md) guide
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-01-19 15:29 UTC, markxnelson commented on images/nginx/rootfs/Dockerfile
> +  && microdnf install yum \
don't install yum, just use microdnf

2021-01-19 16:07 UTC, markxnelson requested changes
don't install yum, just use microdnf

2021-01-20 13:20 UTC, lake-of-dreams commented on images/nginx/rootfs/Dockerfile
> +  && microdnf install yum \
@markxnelson  microdnf does not seem to be installing latest packages, for example
1/ Before introducing `yum` , microdnf was already installing libxml2. - see https://github.com/verrazzano/ingress-nginx/blob/oracle-build-from-source/images/nginx/rootfs/Dockerfile#L54 . This installs `libxml2-devel-2.9.7-7.0.1.el8.x86_64`.
2/ The scanning report https://build.verrazzano.io/view/oracle-build-from-source/job/ingress-nginx/job/bfs%252Fvz1769/1/artifact/scanning-report.json shows a vulnerability with this version.
3/ If we do microdnf update, nothing happens.
4/ After introducing `yum` , libxml2 is updated to libxml2-2.9.7-8.0.1.el8.x86_64 which is the fixed version.

Please suggest.

2021-01-20 14:32 UTC, lake-of-dreams commented on images/nginx/rootfs/Dockerfile
> +  && microdnf install yum \
One thing I can try is specifying the version with `microdnf install` - will try that

2021-01-21 09:01 UTC, lake-of-dreams commented on images/nginx/rootfs/Dockerfile
> +  && microdnf install yum \
fixed.

2021-01-21 10:07 UTC, lake-of-dreams commented
> don't install yum, just use microdnf

implemented

2021-01-22 13:12 UTC, markxnelson approved these changes

2021-01-22 13:18 UTC, merged